name: 'C++ CI'

on:
  push:
    branches:
      - main
      - feature/github_actions

jobs:
  build_macos:
    runs-on: macos-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - run: brew install cmake boost
      - run: brew install cmake cpack-deb 
      - run: cmake . -DPATCH_VERSION=${{ github.run_number }}
      - run: cmake . -DCMAKE_INSTALL_PREFIX=install
      - run: cmake --build .
      - run: cmake --build . --target test

      - run: cmake --build . --target package
      - name: Create Release (macOS)
        id: create_release_macos
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.run_number }}
          release_name: Release ${{ github.run_number }} (macOS)
          draft: false
          prerelease: false
      - name: Upload Release Asset (macOS)
        id: upload-release-asset-macos
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release_macos.outputs.upload_url }}
          asset_path: ./helloworld-0.0.${{ github.run_number }}-macOS.dmg
          asset_name: helloworld-0.0.${{ github.run_number }}-macOS.dmg
          asset_content_type: application/x-apple-diskimage

